version: '3.8'

services:
  weather-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./views:/usr/src/app/views  # Mount views directory for live updates